# Generated by Django 5.2.6 on 2025-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_add_descripcion_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='descripcion_personalizada',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción Personalizada del Producto'),
        ),
    ]
