# Generated by Django 5.2.6 on 2025-09-12 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_itempedido_descripcion_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío. Puede ser 0 si es gratuito.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Envío'),
        ),
    ]
