# Generated by Django 5.2.6 on 2025-09-11 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('confeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confecciones.confeccion')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='cuentas.cuenta')),
            ],
        ),
    ]
