# Generated by Django 5.2.6 on 2025-09-11 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de Entrega Prometida')),
                ('fecha_terminado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Terminación')),
                ('contacto', models.CharField(max_length=100, verbose_name='Persona de Contacto')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('diseno', 'En Diseño'), ('corte', 'En Corte'), ('confeccion', 'En Confección'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('prioritario', 'Prioritario')], default='normal', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confecciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confeccion', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Confección',
                'verbose_name_plural': 'Confecciones',
                'ordering': ['prioridad', 'fecha_entrega'],
                'permissions': [('can_manage_confecciones', 'Puede gestionar confecciones')],
            },
        ),
        migrations.CreateModel(
            name='DetalleConfeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(choices=[('CAMISETA', 'Camiseta'), ('SHORT', 'Short'), ('MEDIAS', 'Medias'), ('MUSCULOSA', 'Musculosa'), ('CANGURO', 'Canguro con pantalón'), ('PANTALON', 'Pantalón'), ('GORRA', 'Gorra'), ('BUZO', 'Buzo'), ('CHAQUETA', 'Chaqueta'), ('OTRO', 'Otro')], max_length=20)),
                ('genero', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('UNISEX', 'Unisex'), ('NIÑO', 'Niño'), ('NIÑA', 'Niña')], max_length=10)),
                ('nombre_diseno', models.CharField(max_length=100, verbose_name='Nombre del Diseño')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('talla', models.CharField(choices=[('XS', 'XS (Extra Small)'), ('S', 'S (Small)'), ('M', 'M (Medium)'), ('L', 'L (Large)'), ('XL', 'XL (Extra Large)'), ('XXL', 'XXL (2X Large)'), ('XXXL', 'XXXL (3X Large)'), ('UNITALLA', 'Unitalla')], max_length=10)),
                ('color_principal', models.CharField(max_length=50, verbose_name='Color Principal')),
                ('colores_secundarios', models.CharField(blank=True, max_length=200, verbose_name='Colores Secundarios')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Específicas')),
                ('confeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='confecciones.confeccion')),
            ],
            options={
                'verbose_name': 'Detalle de Confección',
                'verbose_name_plural': 'Detalles de Confección',
            },
        ),
        migrations.CreateModel(
            name='ItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Item')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_adicionales', to='confecciones.detalleconfeccion')),
            ],
            options={
                'verbose_name': 'Item Adicional',
                'verbose_name_plural': 'Items Adicionales',
            },
        ),
    ]
